create table if not exists CcdVisit (
       ccdVisitId BIGINT,
       visitId INTEGER,
       ccdName CHAR(3),
       raftName CHAR(3),
       filterName CHAR(1),
       nExposures INT,
       ra DOUBLE,
       decl DOUBLE,
       zenithDistance FLOAT,
       llcx INTEGER,
       llcy INTEGER,
       ulcx INTEGER,
       ulcy INTEGER,
       urcx INTEGER,
       urcy INTEGER,
       lrcx INTEGER,
       lrcy INTEGER,
       xSize INTEGER,
       ySize INTEGER,
       obsStart TIMESTAMP,
       expMidpt DOUBLE,
       expTime DOUBLE,
       darkTime DOUBLE,
       ccdTemp FLOAT,
       binX INTEGER,
       binY INTEGER,
       WCS BLOB,
       zeroPoint FLOAT,
       seeing FLOAT,
       skyBg FLOAT,
       skyNoise FLOAT,
       flags INTEGER,
       project CHAR(30),
       primary key (ccdVisitId, project)
       )
